events {
    worker_connections 1024;
}

http {
    # Default deny
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }

    server {
        listen 443 ssl default_server;
        server_name _;
        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        return 444;
    }

    # Upstream - k3s nodes
    upstream k3s_cluster {
        server k3d-forge-agent-0:30080 max_fails=1 fail_timeout=5s;
        server k3d-forge-agent-1:30080 max_fails=1 fail_timeout=5s;
    }

    # HTTP -> HTTPS redirect
    server {
        listen 80;
        server_name forge.mechanicus.local;
        return 301 https://$host$request_uri;
    }

    # Main HTTPS server
    server {
        listen 443 ssl;
        server_name forge.mechanicus.local;

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;

        location / {
            # IP allow list
            #allow 127.0.0.1;
            #allow 172.16.0.0/12;
            #allow 10.0.0.0/8;
            #deny all;

            #return 200 "The Forge stands ready.\n";
            #add_header Content-Type text/plain;

            proxy_pass http://k3s_cluster;
            proxy_connect_timeout 1s;
            client_max_body_size 500M;
            proxy_send_timeout 1800;
            proxy_read_timeout 1800;
            send_timeout 1800;

            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}