set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
"-set rtp+=~/.vim/bundle/Vundle.vim
"-call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
"-Plugin 'VundleVim/Vundle.vim'

" Copilot
"-Plugin 'github/copilot.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
"-call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

if v:progname =~? "evim"
  finish
endif
set nocompatible
set nowrap
set tabstop=4
syn on
set nocp
set nobk
set ai
set si
set ru
set sc
set vb
set wmnu
set smd
set is
" set ic " ignore case
set scs
set noeb
set nosol
set bs=2
set shm=at
set ch=2
filetype plugin indent on
set bsdir=last
set shiftwidth=4
set softtabstop=4
set backspace=indent,eol,start
set nocompatible
set hlsearch
set incsearch
set autoindent
set textwidth=0
set ruler
set history=50
set showcmd
set showmatch
colorscheme delek
set noerrorbells
"oremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm
set pastetoggle=<F3>
map <F2> :%s/\s*$//g<cr>:noh<cr>''
inoremap <C-v> <esc>:set paste<cr>mui<C-R>+<esc>mv'uV'v=:set nopaste<cr>
set backspace=indent,eol,start
if has("vms")
  set nobackup
else
  set nobackup
endif
set history=50
set ruler
set showcmd
set incsearch
map Q gq
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif
if has("autocmd")
  filetype plugin indent on
  augroup vimrcEx
  au!
  autocmd FileType text setlocal textwidth=78
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
  augroup END
else
  set autoindent
endif

" default | elflord | lunaperche | pablo | sorbet | wildcharm
colorscheme sorbet
